// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/stylekit": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/stylekit";
  };
  "pages/home/Home.tsx": {
    id: "pages/home/Home";
    page: "/";
  };
  "pages/stylekit/Stylekit.tsx": {
    id: "pages/stylekit/Stylekit";
    page: "/stylekit";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/home/Home": typeof import("./app/pages/home/Home.tsx");
  "pages/stylekit/Stylekit": typeof import("./app/pages/stylekit/Stylekit.tsx");
};